# Add UpDesk UI translations to all language files
$langDir = "C:\Users\cri\Desktop\rustdesk-1.4.6\src\lang"

$translations = @{
  "ar"    = "        (`"Your ID`", `"معرّفك`"),`n        (`"Copy`", `"نسخ`"),`n        (`"Quick Support`", `"دعم سريع`"),`n        (`"Ready for assistance`", `"جاهز للمساعدة`"),`n        (`"Protected connection (end-to-end encrypted)`", `"اتصال محمي (مشفّر من طرف إلى طرف)`"),`n        (`"Share your ID code with the technician`", `"شارك رمز معرّفك مع الفني`"),`n        (`"Connecting to server...`", `"جارٍ الاتصال بالخادم...`"),`n        (`"Online`", `"متصل`"),`n        (`"Offline`", `"غير متصل`"),"
  "be"    = "        (`"Your ID`", `"Ваш ID`"),`n        (`"Copy`", `"Капіяваць`"),`n        (`"Quick Support`", `"Хуткая падтрымка`"),`n        (`"Ready for assistance`", `"Гатоў да дапамогі`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Абароненае злучэнне (зашыфраванае)`"),`n        (`"Share your ID code with the technician`", `"Падзяліцеся кодам ID з тэхнікам`"),`n        (`"Connecting to server...`", `"Злучэнне з серверам...`"),`n        (`"Online`", `"У сетцы`"),`n        (`"Offline`", `"Не ў сетцы`"),"
  "bg"    = "        (`"Your ID`", `"Вашият ID`"),`n        (`"Copy`", `"Копирай`"),`n        (`"Quick Support`", `"Бърза поддръжка`"),`n        (`"Ready for assistance`", `"Готов за помощ`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Защитена връзка (криптирана от край до край)`"),`n        (`"Share your ID code with the technician`", `"Споделете вашия ID код с техника`"),`n        (`"Connecting to server...`", `"Свързване към сървъра...`"),`n        (`"Online`", `"Онлайн`"),`n        (`"Offline`", `"Офлайн`"),"
  "ca"    = "        (`"Your ID`", `"El teu ID`"),`n        (`"Copy`", `"Copia`"),`n        (`"Quick Support`", `"Suport rapid`"),`n        (`"Ready for assistance`", `"Preparat per a l'assistencia`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Connexio protegida (xifrada d'extrem a extrem)`"),`n        (`"Share your ID code with the technician`", `"Comparteix el teu codi ID amb el tecnic`"),`n        (`"Connecting to server...`", `"Connectant al servidor...`"),`n        (`"Online`", `"En linia`"),`n        (`"Offline`", `"Fora de linia`"),"
  "cn"    = "        (`"Your ID`", `"您的ID`"),`n        (`"Copy`", `"复制`"),`n        (`"Quick Support`", `"快速支持`"),`n        (`"Ready for assistance`", `"准备好提供协助`"),`n        (`"Protected connection (end-to-end encrypted)`", `"受保护的连接（端到端加密）`"),`n        (`"Share your ID code with the technician`", `"将您的ID代码分享给技术员`"),`n        (`"Connecting to server...`", `"正在连接服务器...`"),`n        (`"Online`", `"在线`"),`n        (`"Offline`", `"离线`"),"
  "cs"    = "        (`"Your ID`", `"Vaše ID`"),`n        (`"Copy`", `"Kopírovat`"),`n        (`"Quick Support`", `"Rychlá podpora`"),`n        (`"Ready for assistance`", `"Připraven k pomoci`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Chráněné připojení (šifrované end-to-end)`"),`n        (`"Share your ID code with the technician`", `"Sdílejte svůj kód ID s technikem`"),`n        (`"Connecting to server...`", `"Připojování k serveru...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "da"    = "        (`"Your ID`", `"Dit ID`"),`n        (`"Copy`", `"Kopier`"),`n        (`"Quick Support`", `"Hurtig support`"),`n        (`"Ready for assistance`", `"Klar til assistance`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Beskyttet forbindelse (end-to-end krypteret)`"),`n        (`"Share your ID code with the technician`", `"Del din ID-kode med teknikeren`"),`n        (`"Connecting to server...`", `"Opretter forbindelse til server...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "de"    = "        (`"Your ID`", `"Ihre ID`"),`n        (`"Copy`", `"Kopieren`"),`n        (`"Quick Support`", `"Schnellhilfe`"),`n        (`"Ready for assistance`", `"Bereit zur Unterstutzung`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Geschutzte Verbindung (Ende-zu-Ende verschlusselt)`"),`n        (`"Share your ID code with the technician`", `"Teilen Sie Ihren ID-Code mit dem Techniker`"),`n        (`"Connecting to server...`", `"Verbindung zum Server...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "el"    = "        (`"Your ID`", `"Το ID σας`"),`n        (`"Copy`", `"Αντιγραφή`"),`n        (`"Quick Support`", `"Γρήγορη υποστήριξη`"),`n        (`"Ready for assistance`", `"Έτοιμος για βοήθεια`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Προστατευμένη σύνδεση (κρυπτογραφημένη)`"),`n        (`"Share your ID code with the technician`", `"Μοιραστείτε τον κωδικό ID σας με τον τεχνικό`"),`n        (`"Connecting to server...`", `"Σύνδεση με διακομιστή...`"),`n        (`"Online`", `"Σε σύνδεση`"),`n        (`"Offline`", `"Εκτός σύνδεσης`"),"
  "eo"    = "        (`"Your ID`", `"Via ID`"),`n        (`"Copy`", `"Kopii`"),`n        (`"Quick Support`", `"Rapida subteno`"),`n        (`"Ready for assistance`", `"Preta helpi`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Protektita konekto (cifrita de fino al fino)`"),`n        (`"Share your ID code with the technician`", `"Kunsigu vian ID-kodon kun la teknikisto`"),`n        (`"Connecting to server...`", `"Konektante al servilo...`"),`n        (`"Online`", `"Rete`"),`n        (`"Offline`", `"Eksterrete`"),"
  "es"    = "        (`"Your ID`", `"Tu ID`"),`n        (`"Copy`", `"Copiar`"),`n        (`"Quick Support`", `"Soporte rapido`"),`n        (`"Ready for assistance`", `"Listo para asistencia`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Conexion protegida (cifrado de extremo a extremo)`"),`n        (`"Share your ID code with the technician`", `"Comparte tu codigo ID con el tecnico`"),`n        (`"Connecting to server...`", `"Conectando al servidor...`"),`n        (`"Online`", `"En linea`"),`n        (`"Offline`", `"Sin conexion`"),"
  "et"    = "        (`"Your ID`", `"Teie ID`"),`n        (`"Copy`", `"Kopeeri`"),`n        (`"Quick Support`", `"Kiirtugi`"),`n        (`"Ready for assistance`", `"Valmis abistama`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Kaitstud uhendus (otsast lopuni krüptitud)`"),`n        (`"Share your ID code with the technician`", `"Jagage oma ID-koodi tehnikuga`"),`n        (`"Connecting to server...`", `"Ühendamine serveriga...`"),`n        (`"Online`", `"Võrgus`"),`n        (`"Offline`", `"Võrguühenduseta`"),"
  "eu"    = "        (`"Your ID`", `"Zure IDa`"),`n        (`"Copy`", `"Kopiatu`"),`n        (`"Quick Support`", `"Laguntza azkarra`"),`n        (`"Ready for assistance`", `"Prest laguntzeko`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Konexio babestua (muturretik muturrera enkriptatua)`"),`n        (`"Share your ID code with the technician`", `"Partekatu zure ID kodea teknikariarekin`"),`n        (`"Connecting to server...`", `"Zerbitzarira konektatzen...`"),`n        (`"Online`", `"Sarean`"),`n        (`"Offline`", `"Sare gabe`"),"
  "fa"    = "        (`"Your ID`", `"شناسه شما`"),`n        (`"Copy`", `"کپی`"),`n        (`"Quick Support`", `"پشتیبانی سریع`"),`n        (`"Ready for assistance`", `"آماده کمک`"),`n        (`"Protected connection (end-to-end encrypted)`", `"اتصال محافظت‌شده (رمزنگاری سرتاسری)`"),`n        (`"Share your ID code with the technician`", `"کد شناسه خود را با تکنسین به اشتراک بگذارید`"),`n        (`"Connecting to server...`", `"در حال اتصال به سرور...`"),`n        (`"Online`", `"آنلاین`"),`n        (`"Offline`", `"آفلاین`"),"
  "fi"    = "        (`"Your ID`", `"Sinun ID`"),`n        (`"Copy`", `"Kopioi`"),`n        (`"Quick Support`", `"Pikatuki`"),`n        (`"Ready for assistance`", `"Valmis avustamaan`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Suojattu yhteys (paasta paahan salattu)`"),`n        (`"Share your ID code with the technician`", `"Jaa ID-koodisi teknikon kanssa`"),`n        (`"Connecting to server...`", `"Yhdistetaan palvelimeen...`"),`n        (`"Online`", `"Verkossa`"),`n        (`"Offline`", `"Ei verkossa`"),"
  "fr"    = "        (`"Your ID`", `"Votre ID`"),`n        (`"Copy`", `"Copier`"),`n        (`"Quick Support`", `"Assistance rapide`"),`n        (`"Ready for assistance`", `"Pret pour l'assistance`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Connexion protegee (chiffree de bout en bout)`"),`n        (`"Share your ID code with the technician`", `"Partagez votre code ID avec le technicien`"),`n        (`"Connecting to server...`", `"Connexion au serveur...`"),`n        (`"Online`", `"En ligne`"),`n        (`"Offline`", `"Hors ligne`"),"
  "ge"    = "        (`"Your ID`", `"თქვენი ID`"),`n        (`"Copy`", `"კოპირება`"),`n        (`"Quick Support`", `"სწრაფი მხარდაჭერა`"),`n        (`"Ready for assistance`", `"მზადაა დახმარებისთვის`"),`n        (`"Protected connection (end-to-end encrypted)`", `"დაცული კავშირი (დაშიფრული)`"),`n        (`"Share your ID code with the technician`", `"გაუზიარეთ ID კოდი ტექნიკოსს`"),`n        (`"Connecting to server...`", `"სერვერთან დაკავშირება...`"),`n        (`"Online`", `"ონლაინ`"),`n        (`"Offline`", `"ოფლაინ`"),"
  "he"    = "        (`"Your ID`", `"ה-ID שלך`"),`n        (`"Copy`", `"העתק`"),`n        (`"Quick Support`", `"תמיכה מהירה`"),`n        (`"Ready for assistance`", `"מוכן לסיוע`"),`n        (`"Protected connection (end-to-end encrypted)`", `"חיבור מוגן (מוצפן מקצה לקצה)`"),`n        (`"Share your ID code with the technician`", `"שתף את קוד ה-ID שלך עם הטכנאי`"),`n        (`"Connecting to server...`", `"מתחבר לשרת...`"),`n        (`"Online`", `"מחובר`"),`n        (`"Offline`", `"לא מחובר`"),"
  "hr"    = "        (`"Your ID`", `"Vaš ID`"),`n        (`"Copy`", `"Kopiraj`"),`n        (`"Quick Support`", `"Brza podrška`"),`n        (`"Ready for assistance`", `"Spreman za pomoc`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Zaštićena veza (šifrirana s kraja na kraj)`"),`n        (`"Share your ID code with the technician`", `"Podijelite svoj ID kod s tehnicarom`"),`n        (`"Connecting to server...`", `"Spajanje na poslužitelj...`"),`n        (`"Online`", `"Na mrezi`"),`n        (`"Offline`", `"Izvan mreze`"),"
  "hu"    = "        (`"Your ID`", `"Az On azonositoja`"),`n        (`"Copy`", `"Masolas`"),`n        (`"Quick Support`", `"Gyors tamogatas`"),`n        (`"Ready for assistance`", `"Keszen all a segitsegnyujtasra`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Vedett kapcsolat (vegponttol vegpontig titkositott)`"),`n        (`"Share your ID code with the technician`", `"Ossza meg azonositojat a technikussal`"),`n        (`"Connecting to server...`", `"Csatlakozas a szerverhez...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "id"    = "        (`"Your ID`", `"ID Anda`"),`n        (`"Copy`", `"Salin`"),`n        (`"Quick Support`", `"Dukungan Cepat`"),`n        (`"Ready for assistance`", `"Siap untuk bantuan`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Koneksi terlindungi (terenkripsi ujung-ke-ujung)`"),`n        (`"Share your ID code with the technician`", `"Bagikan kode ID Anda dengan teknisi`"),`n        (`"Connecting to server...`", `"Menghubungkan ke server...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "ja"    = "        (`"Your ID`", `"あなたのID`"),`n        (`"Copy`", `"コピー`"),`n        (`"Quick Support`", `"クイックサポート`"),`n        (`"Ready for assistance`", `"サポート準備完了`"),`n        (`"Protected connection (end-to-end encrypted)`", `"保護された接続（エンドツーエンド暗号化）`"),`n        (`"Share your ID code with the technician`", `"IDコードをサポート担当者と共有してください`"),`n        (`"Connecting to server...`", `"サーバーに接続中...`"),`n        (`"Online`", `"オンライン`"),`n        (`"Offline`", `"オフライン`"),"
  "ko"    = "        (`"Your ID`", `"내 ID`"),`n        (`"Copy`", `"복사`"),`n        (`"Quick Support`", `"빠른 지원`"),`n        (`"Ready for assistance`", `"지원 준비 완료`"),`n        (`"Protected connection (end-to-end encrypted)`", `"보호된 연결 (종단 간 암호화)`"),`n        (`"Share your ID code with the technician`", `"ID 코드를 기술자와 공유하세요`"),`n        (`"Connecting to server...`", `"서버에 연결 중...`"),`n        (`"Online`", `"온라인`"),`n        (`"Offline`", `"오프라인`"),"
  "kz"    = "        (`"Your ID`", `"Сіздің ID`"),`n        (`"Copy`", `"Көшіру`"),`n        (`"Quick Support`", `"Жылдам қолдау`"),`n        (`"Ready for assistance`", `"Көмекке дайын`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Қорғалған қосылым (шифрланған)`"),`n        (`"Share your ID code with the technician`", `"ID кодыңызды маманмен бөлісіңіз`"),`n        (`"Connecting to server...`", `"Серверге қосылу...`"),`n        (`"Online`", `"Желіде`"),`n        (`"Offline`", `"Желіден тыс`"),"
  "lt"    = "        (`"Your ID`", `"Jūsų ID`"),`n        (`"Copy`", `"Kopijuoti`"),`n        (`"Quick Support`", `"Greita pagalba`"),`n        (`"Ready for assistance`", `"Pasiruošęs pagalbai`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Apsaugotas ryšys (šifruotas nuo galo iki galo)`"),`n        (`"Share your ID code with the technician`", `"Pasidalinkite savo ID kodu su techniku`"),`n        (`"Connecting to server...`", `"Jungiamasi prie serverio...`"),`n        (`"Online`", `"Prisijungęs`"),`n        (`"Offline`", `"Neprisijungęs`"),"
  "lv"    = "        (`"Your ID`", `"Jūsu ID`"),`n        (`"Copy`", `"Kopet`"),`n        (`"Quick Support`", `"Atrais atbalsts`"),`n        (`"Ready for assistance`", `"Gatavs palīdzet`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Aizsargats savienojums (šifrets no gala lidz galam)`"),`n        (`"Share your ID code with the technician`", `"Kopīgojiet savu ID kodu ar tehniki`"),`n        (`"Connecting to server...`", `"Pieslegšanas serverim...`"),`n        (`"Online`", `"Tiešsaiste`"),`n        (`"Offline`", `"Bezsaiste`"),"
  "nb"    = "        (`"Your ID`", `"Din ID`"),`n        (`"Copy`", `"Kopier`"),`n        (`"Quick Support`", `"Hurtig stotte`"),`n        (`"Ready for assistance`", `"Klar for assistanse`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Beskyttet tilkobling (ende-til-ende kryptert)`"),`n        (`"Share your ID code with the technician`", `"Del din ID-kode med teknikeren`"),`n        (`"Connecting to server...`", `"Kobler til server...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "nl"    = "        (`"Your ID`", `"Jouw ID`"),`n        (`"Copy`", `"Kopiëren`"),`n        (`"Quick Support`", `"Snelle ondersteuning`"),`n        (`"Ready for assistance`", `"Klaar voor hulp`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Beveiligde verbinding (end-to-end versleuteld)`"),`n        (`"Share your ID code with the technician`", `"Deel uw ID-code met de technicus`"),`n        (`"Connecting to server...`", `"Verbinding maken met server...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "pl"    = "        (`"Your ID`", `"Twoje ID`"),`n        (`"Copy`", `"Kopiuj`"),`n        (`"Quick Support`", `"Szybka pomoc`"),`n        (`"Ready for assistance`", `"Gotowy do pomocy`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Chronione połączenie (szyfrowanie end-to-end)`"),`n        (`"Share your ID code with the technician`", `"Udostępnij swój kod ID technikowi`"),`n        (`"Connecting to server...`", `"Łączenie z serwerem...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "pt_PT" = "        (`"Your ID`", `"O seu ID`"),`n        (`"Copy`", `"Copiar`"),`n        (`"Quick Support`", `"Suporte rapido`"),`n        (`"Ready for assistance`", `"Pronto para assistencia`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Ligacao protegida (cifrada de ponta a ponta)`"),`n        (`"Share your ID code with the technician`", `"Partilhe o seu codigo ID com o tecnico`"),`n        (`"Connecting to server...`", `"A ligar ao servidor...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "ptbr"  = "        (`"Your ID`", `"Seu ID`"),`n        (`"Copy`", `"Copiar`"),`n        (`"Quick Support`", `"Suporte rapido`"),`n        (`"Ready for assistance`", `"Pronto para assistencia`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Conexao protegida (criptografada de ponta a ponta)`"),`n        (`"Share your ID code with the technician`", `"Compartilhe seu codigo ID com o tecnico`"),`n        (`"Connecting to server...`", `"Conectando ao servidor...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "ro"    = "        (`"Your ID`", `"ID-ul dvs.`"),`n        (`"Copy`", `"Copiati`"),`n        (`"Quick Support`", `"Asistenta rapida`"),`n        (`"Ready for assistance`", `"Gata pentru asistenta`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Conexiune protejata (criptata end-to-end)`"),`n        (`"Share your ID code with the technician`", `"Partajati codul dvs. ID cu tehnicianul`"),`n        (`"Connecting to server...`", `"Conectare la server...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "ru"    = "        (`"Your ID`", `"Ваш ID`"),`n        (`"Copy`", `"Копировать`"),`n        (`"Quick Support`", `"Быстрая поддержка`"),`n        (`"Ready for assistance`", `"Готов к помощи`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Защищённое соединение (сквозное шифрование)`"),`n        (`"Share your ID code with the technician`", `"Поделитесь кодом ID с техником`"),`n        (`"Connecting to server...`", `"Подключение к серверу...`"),`n        (`"Online`", `"Онлайн`"),`n        (`"Offline`", `"Офлайн`"),"
  "sc"    = "        (`"Your ID`", `"Su ID`"),`n        (`"Copy`", `"Copia`"),`n        (`"Quick Support`", `"Assistentzia rapida`"),`n        (`"Ready for assistance`", `"Prontu pro s'assistentzia`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Connessione protegida (cifradu)`"),`n        (`"Share your ID code with the technician`", `"Cumpartzi su codice ID cun su tecnicu`"),`n        (`"Connecting to server...`", `"Connessione a su serbidore...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "sk"    = "        (`"Your ID`", `"Vaše ID`"),`n        (`"Copy`", `"Kopirovat`"),`n        (`"Quick Support`", `"Rychla podpora`"),`n        (`"Ready for assistance`", `"Pripraveny na pomoc`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Chranene pripojenie (šifrované end-to-end)`"),`n        (`"Share your ID code with the technician`", `"Zdieľajte svoj kod ID s technikom`"),`n        (`"Connecting to server...`", `"Pripajanie k serveru...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "sl"    = "        (`"Your ID`", `"Vaš ID`"),`n        (`"Copy`", `"Kopiraj`"),`n        (`"Quick Support`", `"Hitra podpora`"),`n        (`"Ready for assistance`", `"Pripravljen za pomoc`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Zaščitena povezava (šifrirana od konca do konca)`"),`n        (`"Share your ID code with the technician`", `"Delite svojo ID kodo s tehnikom`"),`n        (`"Connecting to server...`", `"Povezovanje s strežnikom...`"),`n        (`"Online`", `"V spletu`"),`n        (`"Offline`", `"Brez povezave`"),"
  "sq"    = "        (`"Your ID`", `"ID-ja juaj`"),`n        (`"Copy`", `"Kopjo`"),`n        (`"Quick Support`", `"Mbeshtetje e shpejte`"),`n        (`"Ready for assistance`", `"Gati per ndihme`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Lidhje e mbrojtur (e enkriptuar)`"),`n        (`"Share your ID code with the technician`", `"Ndajeni kodin tuaj ID me teknikun`"),`n        (`"Connecting to server...`", `"Duke u lidhur me serverin...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "sr"    = "        (`"Your ID`", `"Vaš ID`"),`n        (`"Copy`", `"Kopiraj`"),`n        (`"Quick Support`", `"Brza podrška`"),`n        (`"Ready for assistance`", `"Spreman za pomoc`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Zaštićena veza (enkriptovana)`"),`n        (`"Share your ID code with the technician`", `"Podelite ID kod sa tehnicarom`"),`n        (`"Connecting to server...`", `"Povezivanje sa serverom...`"),`n        (`"Online`", `"Na mrezi`"),`n        (`"Offline`", `"Van mreze`"),"
  "sv"    = "        (`"Your ID`", `"Ditt ID`"),`n        (`"Copy`", `"Kopiera`"),`n        (`"Quick Support`", `"Snabb support`"),`n        (`"Ready for assistance`", `"Redo for assistans`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Skyddad anslutning (end-to-end krypterad)`"),`n        (`"Share your ID code with the technician`", `"Dela din ID-kod med teknikern`"),`n        (`"Connecting to server...`", `"Ansluter till server...`"),`n        (`"Online`", `"Online`"),`n        (`"Offline`", `"Offline`"),"
  "ta"    = "        (`"Your ID`", `"உங்கள் ஐடி`"),`n        (`"Copy`", `"நகலெடு`"),`n        (`"Quick Support`", `"விரைவு ஆதரவு`"),`n        (`"Ready for assistance`", `"உதவிக்கு தயார்`"),`n        (`"Protected connection (end-to-end encrypted)`", `"பாதுகாக்கப்பட்ட இணைப்பு`"),`n        (`"Share your ID code with the technician`", `"உங்கள் ஐடி குறியீட்டை பகிரவும்`"),`n        (`"Connecting to server...`", `"சேவையகத்துடன் இணைக்கிறது...`"),`n        (`"Online`", `"ஆன்லைன்`"),`n        (`"Offline`", `"ஆஃப்லைன்`"),"
  "th"    = "        (`"Your ID`", `"ID ของคุณ`"),`n        (`"Copy`", `"คัดลอก`"),`n        (`"Quick Support`", `"การสนับสนุนด่วน`"),`n        (`"Ready for assistance`", `"พร้อมให้ความช่วยเหลือ`"),`n        (`"Protected connection (end-to-end encrypted)`", `"การเชื่อมต่อที่ปลอดภัย`"),`n        (`"Share your ID code with the technician`", `"แบ่งปันรหัส ID ของคุณกับช่างเทคนิค`"),`n        (`"Connecting to server...`", `"กำลังเชื่อมต่อกับเซิร์ฟเวอร์...`"),`n        (`"Online`", `"ออนไลน์`"),`n        (`"Offline`", `"ออฟไลน์`"),"
  "tr"    = "        (`"Your ID`", `"Kimliginiz`"),`n        (`"Copy`", `"Kopyala`"),`n        (`"Quick Support`", `"Hizli Destek`"),`n        (`"Ready for assistance`", `"Yardima hazir`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Korumali baglanti (uctan uca sifreli)`"),`n        (`"Share your ID code with the technician`", `"ID kodunuzu teknisyenle paylasin`"),`n        (`"Connecting to server...`", `"Sunucuya baglanıyor...`"),`n        (`"Online`", `"Çevrimici`"),`n        (`"Offline`", `"Çevrimdışı`"),"
  "tw"    = "        (`"Your ID`", `"您的ID`"),`n        (`"Copy`", `"複製`"),`n        (`"Quick Support`", `"快速支援`"),`n        (`"Ready for assistance`", `"準備好提供協助`"),`n        (`"Protected connection (end-to-end encrypted)`", `"受保護的連線（端對端加密）`"),`n        (`"Share your ID code with the technician`", `"將您的ID代碼分享給技術員`"),`n        (`"Connecting to server...`", `"正在連接伺服器...`"),`n        (`"Online`", `"線上`"),`n        (`"Offline`", `"離線`"),"
  "uk"    = "        (`"Your ID`", `"Ваш ID`"),`n        (`"Copy`", `"Копіювати`"),`n        (`"Quick Support`", `"Швидка підтримка`"),`n        (`"Ready for assistance`", `"Готовий до допомоги`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Захищене зєднання (наскрізне шифрування)`"),`n        (`"Share your ID code with the technician`", `"Поділіться кодом ID з технічним спеціалістом`"),`n        (`"Connecting to server...`", `"Підключення до сервера...`"),`n        (`"Online`", `"Онлайн`"),`n        (`"Offline`", `"Офлайн`"),"
  "vi"    = "        (`"Your ID`", `"ID của bạn`"),`n        (`"Copy`", `"Sao chép`"),`n        (`"Quick Support`", `"Ho tro nhanh`"),`n        (`"Ready for assistance`", `"San sang ho tro`"),`n        (`"Protected connection (end-to-end encrypted)`", `"Ket noi duoc bao ve (ma hoa dau cuoi)`"),`n        (`"Share your ID code with the technician`", `"Chia se ma ID cua ban voi ky thuat vien`"),`n        (`"Connecting to server...`", `"Dang ket noi den may chu...`"),`n        (`"Online`", `"Truc tuyen`"),`n        (`"Offline`", `"Ngoai tuyen`"),"
}

$marker = '("Status",'
$count = 0

foreach ($lang in $translations.Keys) {
    $file = Join-Path $langDir "$lang.rs"
    if (-not (Test-Path $file)) { Write-Host "SKIP (not found): $file"; continue }

    $content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    if ($content -match '"Your ID"') { Write-Host "SKIP (already done): $lang"; continue }

    $insert = $translations[$lang]
    $newContent = $content -replace [regex]::Escape($marker), "$marker`n$insert"
    [System.IO.File]::WriteAllText($file, $newContent, [System.Text.Encoding]::UTF8)
    $count++
    Write-Host "OK: $lang"
}

Write-Host "`nPatched $count language files."
